deploy:
  api_key: {secure: X95d6xNWukqbDsetp1fYzdhObzZ+pJUUVC8Tk8sa3fnHIBU88cBLQkCqYiA54o/mwwzlZW56NRGGyRlNNHBKYAWmINJxEOd7xkcDI0jrhi9yueJmvThPRh76XMDjatEaHnt0qY2L8O5bFkZS02sh4cPn5IFOocV3NScL8MGSq7JL9rL0ig4A4QrauJeIDpfiX/CzvCpiJVhTslJTgab9lJYmKOUP+/yShOKRlDudJWdfD4HaofNaATmvQAQUQlR7MPNlM9lf05umAaQ8585jyqHz7HdJh7PB4+lxDN0PJ6bNiFzOb+12GL9JVIOpY85GT5fm9f68DziDm94ubQTQNC8pP1d2fYiqCu5KuoN0WHjLfUL1Hw9MjtcugPxbPNDBaMqKuO15dZtA+REFxBmgDjPqMU5rBE83LShiLSY37frCtozFoZoiAGVn0EqhbEfGmxWh7++/K/4OD2Rn7U0z191tc2175LA6PoFPjXWmyDLluDqnKx1napkgSdgm88tKSCuidt2Up+7f83gamuGMEOTHZgCRUN9DIn7Ax3tK8FG1lRWJ8Gyn1uh6GZHxX8qqUvH2ubPfck/AUcUNqkxr/whosI9n/eXHdNYeY4gY3MKwfSlJuDkM2Vykjx3Kygn4nISHNqaaE6ZidsHz8jnn+SOo6AGHAepNve9M+vGOwCs=}
  app: elora-io
  provider: heroku
install: npm install
language: node_js
node_js: ['5']
notifications: {slack: 'elora:cLsQ93xDY8AccaL3cBSrjx14'}
