deploy:
  api_key:
    secure: tc24pNvihxHlQyAyAbieVDTJoUBLl8QGCCx/HbDiCHl1Q90l9bnAVG71fMW0FKgInH0IOLrlX60aIJWXCBlm7x/4X7N8akHESI4ZLCGm9/m83G4t9nv9bi0Q1KmlGKgCk2AHduZP9+IZDAWksflqLeWuorBLcD6b2BTje/9ANOq0p53Mta4f6nwOeHr6U5JFOD6tsnCFlbwrOz14x9nFeJZZJ/GtGM0LhWXApzxhrc/oZdxdseA37qReMFen371NCMT/SgggDmIWO7MoDrxLuuzNQQVDKMI8QYJCqdIbUBfqVWuy1MY4MXKHYVOkAVBzKHytKzDJTA0CR+EKolhae0bRyCINZqmwhOzUBKm67pSVXJd/L/fOfVJ2fZQi1rPaMLofezP3Lr7ELMFi3qwHtRE3VHm57EEA83iYjyKMWpwmZFXv1Cc09qFm3dC5bHdJqArWWNDOfAPzFKz6mFfMt8ULaDA1ciOcxipQ7uf0pdQbxMPEfa4CrkCXjo2RBGviHX2FatJCBjr25NmD+UX4D1chC/CL2GznkUyytjvs25OIWBu1FNUB4lfH1PjoJVxPvYrrKkyidcZDR0Wj0kpVtn/hQnos8sTHOF4UbNSYELLJEcsvmcHmqkqO0NuP7/cPrpl0OZTV0gDOPKA6ZKUdX54PqN7Yojp3jabS/JEPJeY=
  app: elora-io
  provider: heroku
  skip_cleanup: true
install: npm install
language: node_js
node_js:
- '5'
notifications:
  slack: elora:cLsQ93xDY8AccaL3cBSrjx14
